export const US_STATES = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'DC', name: 'District of Columbia' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
];

export const US_PORTS = [
  { code: 'BAL', name: 'Baltimore, MD' },
  { code: 'BOS', name: 'Boston, MA' },
  { code: 'CHS', name: 'Charleston, SC' },
  { code: 'GLO', name: 'Galveston, TX' },
  { code: 'HOU', name: 'Houston, TX' },
  { code: 'JAX', name: 'Jacksonville, FL' },
  { code: 'LGB', name: 'Long Beach, CA' },
  { code: 'LAX', name: 'Los Angeles, CA' },
  { code: 'MIA', name: 'Miami, FL' },
  { code: 'MOB', name: 'Mobile, AL' },
  { code: 'NWO', name: 'New Orleans, LA' },
  { code: 'NYC', name: 'New York / New Jersey' },
  { code: 'NFK', name: 'Norfolk, VA' },
  { code: 'OAK', name: 'Oakland, CA' },
  { code: 'PHL', name: 'Philadelphia, PA' },
  { code: 'PDX', name: 'Portland, OR' },
  { code: 'SAV', name: 'Savannah, GA' },
  { code: 'SEA', name: 'Seattle, WA' },
  { code: 'TPA', name: 'Tampa, FL' },
  { code: 'TAC', name: 'Tacoma, WA' },
  { code: 'WIL', name: 'Wilmington, DE' },
];
