export const US_STATES = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'DC', name: 'District of Columbia' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
  { code: 'AS', name: 'American Samoa' },
  { code: 'GU', name: 'Guam' },
  { code: 'MP', name: 'Northern Mariana Islands' },
  { code: 'PR', name: 'Puerto Rico' },
  { code: 'VI', name: 'U.S. Virgin Islands' },
];

export const US_PORTS = [
  // Atlantic — Northeast
  { code: 'PWM', name: 'Portland, ME' },
  { code: 'PSM', name: 'Portsmouth, NH' },
  { code: 'BOS', name: 'Boston, MA' },
  { code: 'PVD', name: 'Providence, RI' },
  { code: 'NLN', name: 'New London, CT' },
  { code: 'NHV', name: 'New Haven, CT' },
  { code: 'BDR', name: 'Bridgeport, CT' },
  { code: 'NYC', name: 'New York / New Jersey' },
  { code: 'ALB', name: 'Albany, NY' },
  { code: 'PHL', name: 'Philadelphia, PA' },
  { code: 'CDM', name: 'Camden, NJ' },
  { code: 'WIL', name: 'Wilmington, DE' },
  { code: 'BAL', name: 'Baltimore, MD' },
  // Atlantic — Mid
  { code: 'ORF', name: 'Norfolk / Hampton Roads, VA' },
  { code: 'PHF', name: 'Newport News, VA' },
  { code: 'RIC', name: 'Richmond, VA' },
  // Atlantic — Southeast
  { code: 'ILM', name: 'Wilmington, NC' },
  { code: 'MRH', name: 'Morehead City, NC' },
  { code: 'CHS', name: 'Charleston, SC' },
  { code: 'GGE', name: 'Georgetown, SC' },
  { code: 'SAV', name: 'Savannah, GA' },
  { code: 'BQK', name: 'Brunswick, GA' },
  { code: 'JAX', name: 'Jacksonville, FL' },
  { code: 'FEC', name: 'Fernandina, FL' },
  { code: 'PCA', name: 'Port Canaveral, FL' },
  { code: 'PEF', name: 'Port Everglades / Fort Lauderdale, FL' },
  { code: 'MIA', name: 'Miami, FL' },
  { code: 'PWP', name: 'Palm Beach, FL' },
  { code: 'KEY', name: 'Key West, FL' },
  // Gulf
  { code: 'TPA', name: 'Tampa, FL' },
  { code: 'MTH', name: 'Manatee, FL' },
  { code: 'PNS', name: 'Pensacola, FL' },
  { code: 'PCS', name: 'Panama City, FL' },
  { code: 'MOB', name: 'Mobile, AL' },
  { code: 'PGL', name: 'Pascagoula, MS' },
  { code: 'GPT', name: 'Gulfport, MS' },
  { code: 'NWO', name: 'New Orleans, LA' },
  { code: 'BTR', name: 'Baton Rouge, LA' },
  { code: 'LCH', name: 'Lake Charles, LA' },
  { code: 'BPT', name: 'Beaumont, TX' },
  { code: 'PRA', name: 'Port Arthur, TX' },
  { code: 'ORG', name: 'Orange, TX' },
  { code: 'HOU', name: 'Houston, TX' },
  { code: 'GLO', name: 'Galveston, TX' },
  { code: 'TXC', name: 'Texas City, TX' },
  { code: 'FRE', name: 'Freeport, TX' },
  { code: 'CRP', name: 'Corpus Christi, TX' },
  { code: 'BRO', name: 'Brownsville, TX' },
  // Pacific — California
  { code: 'SAN', name: 'San Diego, CA' },
  { code: 'LGB', name: 'Long Beach, CA' },
  { code: 'LAX', name: 'Los Angeles, CA' },
  { code: 'HUE', name: 'Port Hueneme, CA' },
  { code: 'SFO', name: 'San Francisco, CA' },
  { code: 'OAK', name: 'Oakland, CA' },
  { code: 'BNC', name: 'Benicia, CA' },
  { code: 'RCH', name: 'Richmond, CA' },
  { code: 'STK', name: 'Stockton, CA' },
  { code: 'SAC', name: 'Sacramento, CA' },
  // Pacific — Northwest
  { code: 'PDX', name: 'Portland, OR' },
  { code: 'CFL', name: 'Coos Bay, OR' },
  { code: 'AST', name: 'Astoria, OR' },
  { code: 'VAN', name: 'Vancouver, WA' },
  { code: 'LGV', name: 'Longview, WA' },
  { code: 'KSO', name: 'Kalama, WA' },
  { code: 'TAC', name: 'Tacoma, WA' },
  { code: 'SEA', name: 'Seattle, WA' },
  { code: 'EVT', name: 'Everett, WA' },
  { code: 'BLI', name: 'Bellingham, WA' },
  // Alaska
  { code: 'ANC', name: 'Anchorage, AK' },
  { code: 'WTR', name: 'Whittier, AK' },
  { code: 'SWD', name: 'Seward, AK' },
  { code: 'VDZ', name: 'Valdez, AK' },
  { code: 'KTN', name: 'Ketchikan, AK' },
  { code: 'JNU', name: 'Juneau, AK' },
  { code: 'DUT', name: 'Dutch Harbor, AK' },
  // Hawaii
  { code: 'HNL', name: 'Honolulu, HI' },
  { code: 'ITO', name: 'Hilo, HI' },
  { code: 'OGG', name: 'Kahului, HI (Maui)' },
  { code: 'LIH', name: 'Nawiliwili, HI (Kauai)' },
  // Great Lakes — east to west
  { code: 'BUF', name: 'Buffalo, NY' },
  { code: 'ROC', name: 'Rochester, NY' },
  { code: 'OSW', name: 'Oswego, NY' },
  { code: 'OGS', name: 'Ogdensburg, NY' },
  { code: 'ERI', name: 'Erie, PA' },
  { code: 'CLE', name: 'Cleveland, OH' },
  { code: 'TOL', name: 'Toledo, OH' },
  { code: 'DET', name: 'Detroit, MI' },
  { code: 'MUS', name: 'Muskegon, MI' },
  { code: 'CHI', name: 'Chicago, IL' },
  { code: 'BRT', name: 'Burns Harbor, IN' },
  { code: 'IND', name: 'Indiana Harbor, IN' },
  { code: 'MKE', name: 'Milwaukee, WI' },
  { code: 'GRB', name: 'Green Bay, WI' },
  { code: 'MAN', name: 'Manitowoc, WI' },
  { code: 'DLH', name: 'Duluth, MN' },
  { code: 'SUW', name: 'Superior, WI' },
  // Inland river ports
  { code: 'MEM', name: 'Memphis, TN' },
  { code: 'STL', name: 'St. Louis, MO' },
  { code: 'CIN', name: 'Cincinnati, OH' },
  { code: 'LOU', name: 'Louisville, KY' },
  { code: 'PIT', name: 'Pittsburgh, PA' },
  { code: 'NSH', name: 'Nashville, TN' },
  // U.S. territories
  { code: 'SJU', name: 'San Juan, PR' },
  { code: 'PSE', name: 'Ponce, PR' },
  { code: 'MAZ', name: 'Mayagüez, PR' },
  { code: 'STT', name: 'Charlotte Amalie, USVI (St. Thomas)' },
  { code: 'STX', name: 'Frederiksted, USVI (St. Croix)' },
  { code: 'GUM', name: 'Apra Harbor, Guam' },
  { code: 'SPN', name: 'Saipan, MP' },
  { code: 'PPG', name: 'Pago Pago, AS' },
];

export const STATE_TO_PORT = {
  AL: 'MOB',
  AK: 'ANC',
  AZ: 'LGB',
  AR: 'HOU',
  CA: 'LGB',
  CO: 'HOU',
  CT: 'NYC',
  DE: 'BAL',
  DC: 'BAL',
  FL: 'JAX',
  GA: 'SAV',
  HI: 'HNL',
  ID: 'TAC',
  IL: 'NYC',
  IN: 'NYC',
  IA: 'HOU',
  KS: 'HOU',
  KY: 'NYC',
  LA: 'NWO',
  ME: 'BOS',
  MD: 'BAL',
  MA: 'BOS',
  MI: 'NYC',
  MN: 'NYC',
  MS: 'GPT',
  MO: 'HOU',
  MT: 'TAC',
  NE: 'HOU',
  NV: 'LGB',
  NH: 'BOS',
  NJ: 'NYC',
  NM: 'HOU',
  NY: 'NYC',
  NC: 'ORF',
  ND: 'NYC',
  OH: 'NYC',
  OK: 'HOU',
  OR: 'PDX',
  PA: 'NYC',
  RI: 'BOS',
  SC: 'CHS',
  SD: 'NYC',
  TN: 'SAV',
  TX: 'HOU',
  UT: 'LGB',
  VT: 'BOS',
  VA: 'ORF',
  WA: 'TAC',
  WV: 'BAL',
  WI: 'NYC',
  WY: 'HOU',
  AS: 'PPG',
  GU: 'GUM',
  MP: 'SPN',
  PR: 'SJU',
  VI: 'STT',
};

export function getPortForState(stateCode) {
  if (!stateCode) return null;
  const portCode = STATE_TO_PORT[stateCode];
  if (!portCode) return null;
  return US_PORTS.find(p => p.code === portCode) || null;
}

