-- Migration: Seed comprehensive car brands and models
-- Dataset: getFrontend/json-car-list (MIT license, 135 brands / 1420 models)

INSERT INTO car_brands (name) VALUES
  ('Aehra'),
  ('Aiways'),
  ('AITO'),
  ('Alfa Romeo'),
  ('Alpine'),
  ('Aion'),
  ('Arcfox'),
  ('Aptera'),
  ('Aston Martin'),
  ('Audi'),
  ('BAIC'),
  ('Baojun'),
  ('Bentley'),
  ('Bestune'),
  ('BMW'),
  ('Bugatti'),
  ('BYD'),
  ('BYTON'),
  ('Cadillac'),
  ('Changan'),
  ('Chery'),
  ('Chevrolet'),
  ('Chrysler'),
  ('Citroën'),
  ('Dacia'),
  ('Daewoo'),
  ('Daihatsu'),
  ('Denza'),
  ('Dodge'),
  ('Dongfeng'),
  ('Drako Motors'),
  ('DS Automobiles'),
  ('EdisonFuture'),
  ('Elaris'),
  ('Enovate'),
  ('Evergrande (Hengchi)'),
  ('Evolute'),
  ('Exeed'),
  ('Faraday Future'),
  ('Ferrari'),
  ('Fiat'),
  ('Fisker'),
  ('Ford'),
  ('Foxtron'),
  ('FREZe'),
  ('Genesis'),
  ('Geely'),
  ('Great Wall'),
  ('Haima'),
  ('Haval'),
  ('HiPhi'),
  ('Honda'),
  ('Hongqi'),
  ('Hummer'),
  ('Hyundai'),
  ('IM Motors'),
  ('Infiniti'),
  ('Isuzu'),
  ('JAC'),
  ('Jaguar'),
  ('Jeep'),
  ('JMC'),
  ('Karma Automotive'),
  ('Kia'),
  ('Koenigsegg'),
  ('Lamborghini'),
  ('Lancia'),
  ('Land Rover'),
  ('Leapmotor'),
  ('Lexus'),
  ('Li Auto'),
  ('Lightyear'),
  ('Lordstown Motors'),
  ('Lotus'),
  ('Lucid'),
  ('Lynk & Co'),
  ('Mahindra'),
  ('Maserati'),
  ('Maxus'),
  ('Maybach'),
  ('Mazda'),
  ('McLaren'),
  ('Mercedes-Benz'),
  ('MG'),
  ('MINI'),
  ('Mitsubishi'),
  ('Mullen Automotive'),
  ('Neta Auto'),
  ('NEVS'),
  ('Nikola'),
  ('NIO'),
  ('Nissan'),
  ('Opel'),
  ('Ora'),
  ('Pagani'),
  ('Perodua'),
  ('Peugeot'),
  ('Piech Automotive'),
  ('Polestar'),
  ('Porsche'),
  ('Proton'),
  ('Qoros'),
  ('Ram'),
  ('Renault'),
  ('Rezvani'),
  ('Rimac'),
  ('Rising Auto'),
  ('Rivian'),
  ('Roewe'),
  ('Rolls-Royce'),
  ('Rover'),
  ('Saab'),
  ('Seat'),
  ('Seres'),
  ('Singulato'),
  ('Skywell'),
  ('Smart'),
  ('Subaru'),
  ('Suzuki'),
  ('Škoda'),
  ('Tata Motors'),
  ('Tesla'),
  ('Thunder Power'),
  ('Toyota'),
  ('Trumpchi'),
  ('VinFast'),
  ('Volkswagen'),
  ('Volvo'),
  ('Voyah'),
  ('Weltmeister'),
  ('Wuling'),
  ('Xiaomi'),
  ('XPeng'),
  ('Zeekr'),
  ('Zotye')
ON CONFLICT (name) DO NOTHING;

INSERT INTO car_models (brand_id, name)
SELECT b.id, m.model_name
FROM car_brands b
JOIN (VALUES
  ('Aehra', 'Sedan'),
  ('Aehra', 'SUV'),
  ('Aiways', 'U5'),
  ('Aiways', 'U6'),
  ('AITO', 'M5'),
  ('AITO', 'M7'),
  ('Alfa Romeo', '145'),
  ('Alfa Romeo', '146'),
  ('Alfa Romeo', '147'),
  ('Alfa Romeo', '155'),
  ('Alfa Romeo', '156'),
  ('Alfa Romeo', '156 Sportwagon'),
  ('Alfa Romeo', '159'),
  ('Alfa Romeo', '159 Sportwagon'),
  ('Alfa Romeo', '164'),
  ('Alfa Romeo', '166'),
  ('Alfa Romeo', '4C'),
  ('Alfa Romeo', 'Brera'),
  ('Alfa Romeo', 'Crosswagon'),
  ('Alfa Romeo', 'GT'),
  ('Alfa Romeo', 'Giulia'),
  ('Alfa Romeo', 'Giulietta'),
  ('Alfa Romeo', 'GTV'),
  ('Alfa Romeo', 'MiTo'),
  ('Alfa Romeo', 'Spider'),
  ('Alfa Romeo', 'Stelvio'),
  ('Alpine', 'A110'),
  ('Alpine', 'A110 GT'),
  ('Alpine', 'A110 R'),
  ('Alpine', 'A110 S'),
  ('Aion', 'Aion LX'),
  ('Aion', 'Aion S'),
  ('Aion', 'Aion V'),
  ('Arcfox', 'Alpha S'),
  ('Arcfox', 'Alpha T'),
  ('Aptera', 'Aptera Solar EV'),
  ('Aston Martin', 'DB11'),
  ('Aston Martin', 'DB9'),
  ('Aston Martin', 'DBS'),
  ('Aston Martin', 'Rapide'),
  ('Aston Martin', 'V12 Vanquish'),
  ('Aston Martin', 'V8 Vantage'),
  ('Aston Martin', 'Vanquish'),
  ('Aston Martin', 'Vantage'),
  ('Aston Martin', 'Virage'),
  ('Audi', '100'),
  ('Audi', '100 Avant'),
  ('Audi', '80'),
  ('Audi', '80 Avant'),
  ('Audi', '80 Cabrio'),
  ('Audi', '90'),
  ('Audi', 'A1'),
  ('Audi', 'A2'),
  ('Audi', 'A3'),
  ('Audi', 'A3 Cabriolet'),
  ('Audi', 'A3 Limuzina'),
  ('Audi', 'A3 Sportback'),
  ('Audi', 'A4'),
  ('Audi', 'A4 Allroad'),
  ('Audi', 'A4 Avant'),
  ('Audi', 'A4 Cabriolet'),
  ('Audi', 'A5'),
  ('Audi', 'A5 Cabriolet'),
  ('Audi', 'A5 Sportback'),
  ('Audi', 'A6'),
  ('Audi', 'A6 Allroad'),
  ('Audi', 'A6 Avant'),
  ('Audi', 'A7'),
  ('Audi', 'A8'),
  ('Audi', 'A8 Long'),
  ('Audi', 'E5'),
  ('Audi', 'Q3'),
  ('Audi', 'Q4 e-tron'),
  ('Audi', 'Q5'),
  ('Audi', 'Q7'),
  ('Audi', 'R8'),
  ('Audi', 'RS4 Cabriolet'),
  ('Audi', 'RS4/RS4 Avant'),
  ('Audi', 'RS5'),
  ('Audi', 'RS6 Avant'),
  ('Audi', 'RS7'),
  ('Audi', 'S3/S3 Sportback'),
  ('Audi', 'S4 Cabriolet'),
  ('Audi', 'S4/S4 Avant'),
  ('Audi', 'S5/S5 Cabriolet'),
  ('Audi', 'S6/RS6'),
  ('Audi', 'S7'),
  ('Audi', 'S8'),
  ('Audi', 'SQ5'),
  ('Audi', 'TT Coupé'),
  ('Audi', 'TT Roadster'),
  ('Audi', 'TTS'),
  ('BAIC', 'EC5'),
  ('BAIC', 'EU-X'),
  ('BAIC', 'EU5'),
  ('BAIC', 'EX360'),
  ('Baojun', '310'),
  ('Baojun', '510'),
  ('Baojun', '530'),
  ('Baojun', 'E100'),
  ('Baojun', 'E200'),
  ('Baojun', 'E300'),
  ('Baojun', 'KiWi EV'),
  ('Baojun', 'RC-5'),
  ('Baojun', 'RC-6'),
  ('Baojun', 'RM-5'),
  ('Baojun', 'RS-3'),
  ('Baojun', 'RS-5'),
  ('Baojun', 'RS-7'),
  ('Bentley', 'Arnage'),
  ('Bentley', 'Azure'),
  ('Bentley', 'Bentayga'),
  ('Bentley', 'Brooklands'),
  ('Bentley', 'Continental'),
  ('Bentley', 'Continental Flying Spur'),
  ('Bentley', 'Continental GT'),
  ('Bentley', 'Continental GTC'),
  ('Bentley', 'Flying Spur'),
  ('Bentley', 'Mulsanne'),
  ('Bestune', 'B70'),
  ('Bestune', 'E01'),
  ('Bestune', 'T77'),
  ('Bestune', 'T99'),
  ('BMW', 'i3'),
  ('BMW', 'i8'),
  ('BMW', 'iX'),
  ('BMW', 'iX3'),
  ('BMW', 'M3'),
  ('BMW', 'M4'),
  ('BMW', 'M5'),
  ('BMW', 'M6'),
  ('BMW', 'Rad 1'),
  ('BMW', 'Rad 1 Cabrio'),
  ('BMW', 'Rad 1 Coupé'),
  ('BMW', 'Rad 2'),
  ('BMW', 'Rad 2 Active Tourer'),
  ('BMW', 'Rad 2 Coupé'),
  ('BMW', 'Rad 2 Gran Tourer'),
  ('BMW', 'Rad 3'),
  ('BMW', 'Rad 3 Cabrio'),
  ('BMW', 'Rad 3 Compact'),
  ('BMW', 'Rad 3 Coupé'),
  ('BMW', 'Rad 3 GT'),
  ('BMW', 'Rad 3 Touring'),
  ('BMW', 'Rad 4'),
  ('BMW', 'Rad 4 Cabrio'),
  ('BMW', 'Rad 4 Gran Coupé'),
  ('BMW', 'Rad 5'),
  ('BMW', 'Rad 5 GT'),
  ('BMW', 'Rad 5 Touring'),
  ('BMW', 'Rad 6'),
  ('BMW', 'Rad 6 Cabrio'),
  ('BMW', 'Rad 6 Coupé'),
  ('BMW', 'Rad 6 Gran Coupé'),
  ('BMW', 'Rad 7'),
  ('BMW', 'Rad 8 Coupé'),
  ('BMW', 'X1'),
  ('BMW', 'X2'),
  ('BMW', 'X3'),
  ('BMW', 'X4'),
  ('BMW', 'X5'),
  ('BMW', 'X6'),
  ('BMW', 'Z3'),
  ('BMW', 'Z3 Coupé'),
  ('BMW', 'Z3 Roadster'),
  ('BMW', 'Z4'),
  ('BMW', 'Z4 Roadster'),
  ('Bugatti', 'Chiron'),
  ('Bugatti', 'Divo'),
  ('Bugatti', 'Veyron'),
  ('BYD', 'Denza'),
  ('BYD', 'Denza Z9 GT EV'),
  ('BYD', 'Dolphin'),
  ('BYD', 'Han'),
  ('BYD', 'Seal'),
  ('BYD', 'Seal 07 DM-i'),
  ('BYD', 'Sealion 07 EV'),
  ('BYD', 'Sealion 7'),
  ('BYD', 'Song Max'),
  ('BYD', 'Tang'),
  ('BYD', 'Yangwang U8'),
  ('BYD', 'Yangwang U9'),
  ('BYD', 'Yuan Plus'),
  ('BYTON', 'K-Byte'),
  ('BYTON', 'M-Byte'),
  ('Cadillac', 'ATS'),
  ('Cadillac', 'BLS'),
  ('Cadillac', 'CT5'),
  ('Cadillac', 'CT6'),
  ('Cadillac', 'CTS'),
  ('Cadillac', 'DeVille'),
  ('Cadillac', 'Eldorado'),
  ('Cadillac', 'Escalade'),
  ('Cadillac', 'Seville'),
  ('Cadillac', 'SRX'),
  ('Cadillac', 'STS'),
  ('Cadillac', 'XT4'),
  ('Cadillac', 'XT5'),
  ('Cadillac', 'XT6'),
  ('Cadillac', 'XTS'),
  ('Changan', 'Alsvin'),
  ('Changan', 'BenBen'),
  ('Changan', 'CS35'),
  ('Changan', 'CS55'),
  ('Changan', 'CS75 Plus'),
  ('Changan', 'Eado'),
  ('Changan', 'UNI-E'),
  ('Changan', 'UNI-K'),
  ('Changan', 'UNI-T'),
  ('Changan', 'UNI-V'),
  ('Chery', 'Arrizo 5'),
  ('Chery', 'Arrizo 5 Plus'),
  ('Chery', 'Arrizo 7'),
  ('Chery', 'Arrizo 8'),
  ('Chery', 'E5'),
  ('Chery', 'QQ'),
  ('Chery', 'Tiggo 2'),
  ('Chery', 'Tiggo 3'),
  ('Chery', 'Tiggo 4'),
  ('Chery', 'Tiggo 5'),
  ('Chery', 'Tiggo 7'),
  ('Chery', 'Tiggo 8'),
  ('Chevrolet', 'Alero'),
  ('Chevrolet', 'Aveo'),
  ('Chevrolet', 'Blazer'),
  ('Chevrolet', 'Camaro'),
  ('Chevrolet', 'Captiva'),
  ('Chevrolet', 'Corvette'),
  ('Chevrolet', 'Cruze'),
  ('Chevrolet', 'Cruze SW'),
  ('Chevrolet', 'Epica'),
  ('Chevrolet', 'Equinox'),
  ('Chevrolet', 'Evanda'),
  ('Chevrolet', 'HHR'),
  ('Chevrolet', 'Kalos'),
  ('Chevrolet', 'Lacetti'),
  ('Chevrolet', 'Lacetti SW'),
  ('Chevrolet', 'Lumina'),
  ('Chevrolet', 'Malibu'),
  ('Chevrolet', 'Matiz'),
  ('Chevrolet', 'Monte Carlo'),
  ('Chevrolet', 'Nubira'),
  ('Chevrolet', 'Orlando'),
  ('Chevrolet', 'Spark'),
  ('Chevrolet', 'Suburban'),
  ('Chevrolet', 'Tacuma'),
  ('Chevrolet', 'Tahoe'),
  ('Chevrolet', 'Trax'),
  ('Chrysler', '300C'),
  ('Chrysler', '300M'),
  ('Chrysler', 'Crossfire'),
  ('Chrysler', 'Grand Voyager'),
  ('Chrysler', 'Neon'),
  ('Chrysler', 'Pacifica'),
  ('Chrysler', 'Plymouth'),
  ('Chrysler', 'PT Cruiser'),
  ('Chrysler', 'Sebring'),
  ('Chrysler', 'Stratus'),
  ('Chrysler', 'Viper'),
  ('Chrysler', 'Vision'),
  ('Chrysler', 'Voyager'),
  ('Citroën', 'Berlingo'),
  ('Citroën', 'C-Crosser'),
  ('Citroën', 'C-Elissée'),
  ('Citroën', 'C-Zero'),
  ('Citroën', 'C1'),
  ('Citroën', 'C2'),
  ('Citroën', 'C3'),
  ('Citroën', 'C3 Aircross'),
  ('Citroën', 'C3 Picasso'),
  ('Citroën', 'C4'),
  ('Citroën', 'C4 Aircross'),
  ('Citroën', 'C4 Cactus'),
  ('Citroën', 'C4 Coupé'),
  ('Citroën', 'C4 Grand Picasso'),
  ('Citroën', 'C4 Sedan'),
  ('Citroën', 'C4 SpaceTourer'),
  ('Citroën', 'C5'),
  ('Citroën', 'C5 Break'),
  ('Citroën', 'C5 Tourer'),
  ('Citroën', 'C5 X'),
  ('Citroën', 'C6'),
  ('Citroën', 'C8'),
  ('Citroën', 'DS3'),
  ('Citroën', 'DS4'),
  ('Citroën', 'DS5'),
  ('Citroën', 'Evasion'),
  ('Citroën', 'Jumper'),
  ('Citroën', 'Jumpy'),
  ('Citroën', 'Nemo'),
  ('Citroën', 'Saxo'),
  ('Citroën', 'Xantia'),
  ('Citroën', 'Xsara'),
  ('Citroën', 'ë-C4'),
  ('Dacia', 'Bigster'),
  ('Dacia', 'Dokker'),
  ('Dacia', 'Duster'),
  ('Dacia', 'Jogger'),
  ('Dacia', 'Lodgy'),
  ('Dacia', 'Logan'),
  ('Dacia', 'Logan MCV'),
  ('Dacia', 'Logan Van'),
  ('Dacia', 'Sandero'),
  ('Dacia', 'Solenza'),
  ('Dacia', 'Spring'),
  ('Daewoo', 'Espero'),
  ('Daewoo', 'Kalos'),
  ('Daewoo', 'Lacetti'),
  ('Daewoo', 'Lanos'),
  ('Daewoo', 'Leganza'),
  ('Daewoo', 'Lublin'),
  ('Daewoo', 'Matiz'),
  ('Daewoo', 'Nexia'),
  ('Daewoo', 'Nubira'),
  ('Daewoo', 'Nubira kombi'),
  ('Daewoo', 'Racer'),
  ('Daewoo', 'Rezzo'),
  ('Daewoo', 'Tacuma'),
  ('Daewoo', 'Tico'),
  ('Daihatsu', 'Altis'),
  ('Daihatsu', 'Atrai'),
  ('Daihatsu', 'Boon'),
  ('Daihatsu', 'Copen'),
  ('Daihatsu', 'Hijet'),
  ('Daihatsu', 'Mira'),
  ('Daihatsu', 'Rocky'),
  ('Daihatsu', 'Sirion'),
  ('Daihatsu', 'Terios'),
  ('Daihatsu', 'Thor'),
  ('Daihatsu', 'Tanto'),
  ('Denza', 'Denza D9'),
  ('Denza', 'Denza N7'),
  ('Denza', 'Denza X'),
  ('Dodge', 'Avenger'),
  ('Dodge', 'Caliber'),
  ('Dodge', 'Challenger'),
  ('Dodge', 'Charger'),
  ('Dodge', 'Dakota'),
  ('Dodge', 'Durango'),
  ('Dodge', 'Grand Caravan'),
  ('Dodge', 'Journey'),
  ('Dodge', 'Magnum'),
  ('Dodge', 'Nitro'),
  ('Dodge', 'RAM'),
  ('Dongfeng', 'Fengon E3'),
  ('Dongfeng', 'Fengon E5'),
  ('Dongfeng', 'Fengon E6'),
  ('Dongfeng', 'Junfeng EV'),
  ('Dongfeng', 'Kangdian EV'),
  ('Drako Motors', 'Dragon'),
  ('Drako Motors', 'GTE'),
  ('DS Automobiles', 'DS 3 Crossback E-Tense'),
  ('DS Automobiles', 'DS 7 Crossback E-Tense'),
  ('DS Automobiles', 'DS 9 E-Tense'),
  ('EdisonFuture', 'EF1-T'),
  ('EdisonFuture', 'EF1-V'),
  ('Elaris', 'Beo'),
  ('Elaris', 'Caro'),
  ('Elaris', 'Dyo'),
  ('Elaris', 'Finn'),
  ('Enovate', 'ME7'),
  ('Enovate', 'ME9'),
  ('Evergrande (Hengchi)', 'Hengchi 1'),
  ('Evergrande (Hengchi)', 'Hengchi 3'),
  ('Evergrande (Hengchi)', 'Hengchi 5'),
  ('Evergrande (Hengchi)', 'Hengchi 6'),
  ('Evergrande (Hengchi)', 'Hengchi 7'),
  ('Evolute', 'i-Joy'),
  ('Evolute', 'i-Pro'),
  ('Evolute', 'i-Sky'),
  ('Evolute', 'i-Van'),
  ('Exeed', 'TX'),
  ('Exeed', 'VX'),
  ('Faraday Future', 'FF 71'),
  ('Faraday Future', 'FF 81'),
  ('Faraday Future', 'FF 91'),
  ('Ferrari', '348'),
  ('Ferrari', '360 Modena'),
  ('Ferrari', '458 Italia'),
  ('Ferrari', '488 GTB'),
  ('Ferrari', '512'),
  ('Ferrari', '550 Maranello'),
  ('Ferrari', '575M Maranello'),
  ('Ferrari', '599 GTB Fiorano'),
  ('Ferrari', '612 Scaglietti'),
  ('Ferrari', '812 Superfast'),
  ('Ferrari', 'California'),
  ('Ferrari', 'Enzo'),
  ('Ferrari', 'F12berlinetta'),
  ('Ferrari', 'F355'),
  ('Ferrari', 'F430'),
  ('Ferrari', 'FF'),
  ('Ferrari', 'LaFerrari'),
  ('Ferrari', 'Portofino'),
  ('Ferrari', 'Roma'),
  ('Ferrari', 'SF90 Stradale'),
  ('Fiat', '124 Spider'),
  ('Fiat', '500'),
  ('Fiat', '500C'),
  ('Fiat', '500L'),
  ('Fiat', '500X'),
  ('Fiat', '850'),
  ('Fiat', 'Barchetta'),
  ('Fiat', 'Brava'),
  ('Fiat', 'Cinquecento'),
  ('Fiat', 'Coupé'),
  ('Fiat', 'Croma'),
  ('Fiat', 'Doblo'),
  ('Fiat', 'Doblo Cargo'),
  ('Fiat', 'Doblo Kombi'),
  ('Fiat', 'Ducato'),
  ('Fiat', 'Ducato Van'),
  ('Fiat', 'Freemont'),
  ('Fiat', 'Fullback'),
  ('Fiat', 'Grande Punto'),
  ('Fiat', 'Idea'),
  ('Fiat', 'Linea'),
  ('Fiat', 'Marea'),
  ('Fiat', 'Marea Weekend'),
  ('Fiat', 'Multipla'),
  ('Fiat', 'Palio'),
  ('Fiat', 'Panda'),
  ('Fiat', 'Panda 4x4'),
  ('Fiat', 'Punto'),
  ('Fiat', 'Punto Cabrio'),
  ('Fiat', 'Punto Evo'),
  ('Fiat', 'Qubo'),
  ('Fiat', 'Scudo'),
  ('Fiat', 'Sedici'),
  ('Fiat', 'Seicento'),
  ('Fiat', 'Stilo'),
  ('Fiat', 'Strada'),
  ('Fiat', 'Talento'),
  ('Fiat', 'Tipo'),
  ('Fiat', 'Ulysse'),
  ('Fiat', 'Uno'),
  ('Fisker', 'Alaska'),
  ('Fisker', 'Atlantic'),
  ('Fisker', 'Karma'),
  ('Fisker', 'Ocean'),
  ('Fisker', 'Pear'),
  ('Fisker', 'Ronin'),
  ('Ford', 'B-MAX'),
  ('Ford', 'C-MAX'),
  ('Ford', 'Cougar'),
  ('Ford', 'Edge'),
  ('Ford', 'Escort'),
  ('Ford', 'Escort Cabrio'),
  ('Ford', 'Escort kombi'),
  ('Ford', 'Explorer'),
  ('Ford', 'Fiesta'),
  ('Ford', 'Fiesta Courier'),
  ('Ford', 'Focus'),
  ('Ford', 'Focus C-MAX'),
  ('Ford', 'Focus Cabrio'),
  ('Ford', 'Focus kombi'),
  ('Ford', 'Galaxy'),
  ('Ford', 'Grand C-MAX'),
  ('Ford', 'Ka'),
  ('Ford', 'Kuga'),
  ('Ford', 'Mondeo'),
  ('Ford', 'Mondeo kombi'),
  ('Ford', 'Mustang'),
  ('Ford', 'Orion'),
  ('Ford', 'Puma'),
  ('Ford', 'Ranger'),
  ('Ford', 'S-MAX'),
  ('Ford', 'Sierra'),
  ('Ford', 'Streetka'),
  ('Ford', 'Tourneo Connect'),
  ('Ford', 'Tourneo Courier'),
  ('Ford', 'Transit'),
  ('Ford', 'Transit Bus'),
  ('Ford', 'Transit Connect'),
  ('Ford', 'Transit Courier'),
  ('Ford', 'Transit Custom'),
  ('Ford', 'Transit Van'),
  ('Foxtron', 'Model C'),
  ('Foxtron', 'Model E'),
  ('Foxtron', 'Model T'),
  ('FREZe', 'Nikrob'),
  ('Genesis', 'G70'),
  ('Genesis', 'G80'),
  ('Genesis', 'G90'),
  ('Genesis', 'GV60'),
  ('Genesis', 'GV70'),
  ('Genesis', 'GV80'),
  ('Geely', 'Atlas'),
  ('Geely', 'Binrui'),
  ('Geely', 'Borui'),
  ('Geely', 'Emgrand 7'),
  ('Geely', 'Emgrand GT'),
  ('Geely', 'Emgrand X7'),
  ('Geely', 'Icon'),
  ('Geely', 'Okavango'),
  ('Geely', 'Panda'),
  ('Geely', 'Tugella'),
  ('Great Wall', 'C30'),
  ('Great Wall', 'C50'),
  ('Great Wall', 'Hover'),
  ('Great Wall', 'Poer'),
  ('Great Wall', 'Steed 5'),
  ('Great Wall', 'Tank 300'),
  ('Great Wall', 'Tank 500'),
  ('Great Wall', 'Wingle 7'),
  ('Haima', '7X'),
  ('Haima', 'E3'),
  ('Haima', 'E6'),
  ('Haima', 'S5'),
  ('Haval', 'Big Dog'),
  ('Haval', 'Chulian'),
  ('Haval', 'Dargo'),
  ('Haval', 'F7'),
  ('Haval', 'F7x'),
  ('Haval', 'H6'),
  ('Haval', 'H9'),
  ('Haval', 'Jolion'),
  ('HiPhi', 'HiPhi X'),
  ('HiPhi', 'HiPhi Y'),
  ('HiPhi', 'HiPhi Z'),
  ('Honda', 'Accord'),
  ('Honda', 'Accord Coupé'),
  ('Honda', 'City'),
  ('Honda', 'Civic'),
  ('Honda', 'Civic Aerodeck'),
  ('Honda', 'Civic Coupé'),
  ('Honda', 'Civic Tourer'),
  ('Honda', 'Civic Type R'),
  ('Honda', 'Concerto'),
  ('Honda', 'CR-V'),
  ('Honda', 'CR-Z'),
  ('Honda', 'Element'),
  ('Honda', 'FR-V'),
  ('Honda', 'HR-V'),
  ('Honda', 'Insight'),
  ('Honda', 'Integra'),
  ('Honda', 'Jazz'),
  ('Honda', 'Legend'),
  ('Honda', 'Logo'),
  ('Honda', 'NSX'),
  ('Honda', 'Prelude'),
  ('Honda', 'S2000'),
  ('Honda', 'Shuttle'),
  ('Honda', 'Stream'),
  ('Hongqi', 'E-HS9'),
  ('Hongqi', 'H5'),
  ('Hongqi', 'H9'),
  ('Hongqi', 'L5'),
  ('Hongqi', 'S9'),
  ('Hummer', 'H2'),
  ('Hummer', 'H3'),
  ('Hyundai', 'Accent'),
  ('Hyundai', 'Atos'),
  ('Hyundai', 'Azera'),
  ('Hyundai', 'Coupé'),
  ('Hyundai', 'Creta'),
  ('Hyundai', 'Elantra'),
  ('Hyundai', 'Galloper'),
  ('Hyundai', 'Genesis'),
  ('Hyundai', 'Getz'),
  ('Hyundai', 'Grandeur'),
  ('Hyundai', 'H 350'),
  ('Hyundai', 'H1'),
  ('Hyundai', 'i10'),
  ('Hyundai', 'i20'),
  ('Hyundai', 'i30'),
  ('Hyundai', 'i30 CW'),
  ('Hyundai', 'i40'),
  ('Hyundai', 'i40 CW'),
  ('Hyundai', 'Ioniq'),
  ('Hyundai', 'ix20'),
  ('Hyundai', 'ix35'),
  ('Hyundai', 'Kona'),
  ('Hyundai', 'Lantra'),
  ('Hyundai', 'Matrix'),
  ('Hyundai', 'Palisade'),
  ('Hyundai', 'Santa Fe'),
  ('Hyundai', 'Sonata'),
  ('Hyundai', 'Staria'),
  ('Hyundai', 'Terracan'),
  ('Hyundai', 'Tucson'),
  ('Hyundai', 'Veloster'),
  ('Hyundai', 'Venue'),
  ('Hyundai', 'XG 30'),
  ('IM Motors', 'IM L6'),
  ('IM Motors', 'IM L7'),
  ('Infiniti', 'EX'),
  ('Infiniti', 'FX'),
  ('Infiniti', 'G'),
  ('Infiniti', 'G Coupé'),
  ('Infiniti', 'JX'),
  ('Infiniti', 'M'),
  ('Infiniti', 'Q'),
  ('Infiniti', 'Q30'),
  ('Infiniti', 'Q50'),
  ('Infiniti', 'Q60'),
  ('Infiniti', 'Q70'),
  ('Infiniti', 'QX'),
  ('Infiniti', 'QX30'),
  ('Infiniti', 'QX50'),
  ('Infiniti', 'QX60'),
  ('Infiniti', 'QX70'),
  ('Infiniti', 'QX80'),
  ('Isuzu', 'Amigo'),
  ('Isuzu', 'Ascender'),
  ('Isuzu', 'Axiom'),
  ('Isuzu', 'D-Max'),
  ('Isuzu', 'Hombre'),
  ('Isuzu', 'MU-7'),
  ('Isuzu', 'MU-X'),
  ('Isuzu', 'Rodeo'),
  ('Isuzu', 'Trooper'),
  ('Isuzu', 'VehiCROSS'),
  ('JAC', 'iEV6S'),
  ('JAC', 'iEV7S'),
  ('JAC', 'Refine E6'),
  ('JAC', 'Refine S4'),
  ('JAC', 'Refine S5'),
  ('Jaguar', 'Daimler'),
  ('Jaguar', 'F-Pace'),
  ('Jaguar', 'F-Type'),
  ('Jaguar', 'S-Type'),
  ('Jaguar', 'X-Type'),
  ('Jaguar', 'XE'),
  ('Jaguar', 'XF'),
  ('Jaguar', 'XJ'),
  ('Jaguar', 'XK'),
  ('Jaguar', 'XK8'),
  ('Jeep', 'Cherokee'),
  ('Jeep', 'Commander'),
  ('Jeep', 'Compass'),
  ('Jeep', 'Grand Cherokee'),
  ('Jeep', 'Patriot'),
  ('Jeep', 'Renegade'),
  ('Jeep', 'Wrangler'),
  ('JMC', 'EV6'),
  ('JMC', 'Yuhu EV'),
  ('JMC', 'Yuhu Pickup'),
  ('Karma Automotive', 'Revero'),
  ('Karma Automotive', 'Revero GT'),
  ('Kia', 'Carens'),
  ('Kia', 'Carnival'),
  ('Kia', 'Ceed'),
  ('Kia', 'Ceed SW'),
  ('Kia', 'Cerato'),
  ('Kia', 'Joice'),
  ('Kia', 'K2500'),
  ('Kia', 'Magentis'),
  ('Kia', 'Niro'),
  ('Kia', 'Opirus'),
  ('Kia', 'Optima'),
  ('Kia', 'Picanto'),
  ('Kia', 'Pregio'),
  ('Kia', 'Pride'),
  ('Kia', 'ProCeed'),
  ('Kia', 'Rio'),
  ('Kia', 'Rio Combi'),
  ('Kia', 'Sephia'),
  ('Kia', 'Shuma'),
  ('Kia', 'Sorento'),
  ('Kia', 'Soul'),
  ('Kia', 'Sportage'),
  ('Kia', 'Venga'),
  ('Koenigsegg', 'Agera'),
  ('Koenigsegg', 'CC8S'),
  ('Koenigsegg', 'CCX'),
  ('Koenigsegg', 'Gemera'),
  ('Koenigsegg', 'Jesko'),
  ('Koenigsegg', 'One:1'),
  ('Koenigsegg', 'Regera'),
  ('Lamborghini', 'Aventador'),
  ('Lamborghini', 'Countach'),
  ('Lamborghini', 'Diablo'),
  ('Lamborghini', 'Gallardo'),
  ('Lamborghini', 'Huracán'),
  ('Lamborghini', 'Murciélago'),
  ('Lamborghini', 'Reventón'),
  ('Lamborghini', 'Sian'),
  ('Lamborghini', 'Urus'),
  ('Lamborghini', 'Veneno'),
  ('Lancia', 'Delta'),
  ('Lancia', 'Lybra'),
  ('Lancia', 'Musa'),
  ('Lancia', 'Phedra'),
  ('Lancia', 'Thesis'),
  ('Lancia', 'Ypsilon'),
  ('Land Rover', 'Defender'),
  ('Land Rover', 'Discovery'),
  ('Land Rover', 'Discovery Sport'),
  ('Land Rover', 'Freelander'),
  ('Land Rover', 'Range Rover'),
  ('Land Rover', 'Range Rover Evoque'),
  ('Land Rover', 'Range Rover Sport'),
  ('Land Rover', 'Range Rover Velar'),
  ('Leapmotor', 'B10'),
  ('Leapmotor', 'C01'),
  ('Leapmotor', 'C10'),
  ('Leapmotor', 'C11'),
  ('Leapmotor', 'C16'),
  ('Leapmotor', 'T03'),
  ('Lexus', 'CT'),
  ('Lexus', 'GS'),
  ('Lexus', 'GS 300'),
  ('Lexus', 'GX'),
  ('Lexus', 'IS'),
  ('Lexus', 'IS 200'),
  ('Lexus', 'IS 250 C'),
  ('Lexus', 'IS-F'),
  ('Lexus', 'LS'),
  ('Lexus', 'LX'),
  ('Lexus', 'NX'),
  ('Lexus', 'RC F'),
  ('Lexus', 'RX'),
  ('Lexus', 'RX 300'),
  ('Lexus', 'RX 400h'),
  ('Lexus', 'RX 450h'),
  ('Lexus', 'SC 430'),
  ('Lexus', 'UX'),
  ('Li Auto', 'L7'),
  ('Li Auto', 'L8'),
  ('Li Auto', 'L9'),
  ('Li Auto', 'One'),
  ('Lightyear', 'Lightyear 0'),
  ('Lightyear', 'Lightyear 2'),
  ('Lordstown Motors', 'Endurance'),
  ('Lotus', 'Elan'),
  ('Lotus', 'Elise'),
  ('Lotus', 'Emira'),
  ('Lotus', 'Evija'),
  ('Lotus', 'Evora'),
  ('Lotus', 'Exige'),
  ('Lucid', 'Air'),
  ('Lucid', 'Gravity'),
  ('Lynk & Co', '01'),
  ('Lynk & Co', '03'),
  ('Lynk & Co', '05'),
  ('Lynk & Co', '06'),
  ('Lynk & Co', '07'),
  ('Lynk & Co', '08'),
  ('Lynk & Co', '09'),
  ('Lynk & Co', 'Z10'),
  ('Lynk & Co', 'Z20'),
  ('Lynk & Co', '900'),
  ('Mahindra', 'Bolero'),
  ('Mahindra', 'KUV100'),
  ('Mahindra', 'Marazzo'),
  ('Mahindra', 'Scorpio'),
  ('Mahindra', 'Thar'),
  ('Mahindra', 'TUV300'),
  ('Mahindra', 'XUV300'),
  ('Mahindra', 'XUV500'),
  ('Mahindra', 'XUV700'),
  ('Maserati', '3200 GT'),
  ('Maserati', '4200'),
  ('Maserati', 'Ghibli'),
  ('Maserati', 'GranCabrio'),
  ('Maserati', 'GranTurismo'),
  ('Maserati', 'Levante'),
  ('Maserati', 'MC20'),
  ('Maserati', 'Quattroporte'),
  ('Maxus', 'E Deliver 3'),
  ('Maxus', 'E Deliver 9'),
  ('Maxus', 'MIFA 9'),
  ('Maxus', 'T90 EV'),
  ('Maybach', '57'),
  ('Maybach', '57S'),
  ('Maybach', '62'),
  ('Maybach', '62S'),
  ('Maybach', 'GLS 600'),
  ('Maybach', 'Landaulet'),
  ('Maybach', 'S480'),
  ('Maybach', 'S580'),
  ('Maybach', 'S650'),
  ('Maybach', 'S680'),
  ('Mazda', '121'),
  ('Mazda', '2'),
  ('Mazda', '3'),
  ('Mazda', '323'),
  ('Mazda', '323 Combi'),
  ('Mazda', '323 Coupé'),
  ('Mazda', '323 F'),
  ('Mazda', '5'),
  ('Mazda', '6'),
  ('Mazda', '6 Combi'),
  ('Mazda', '626'),
  ('Mazda', '626 Combi'),
  ('Mazda', 'B-Fighter'),
  ('Mazda', 'B2500'),
  ('Mazda', 'BT'),
  ('Mazda', 'CX-3'),
  ('Mazda', 'CX-30'),
  ('Mazda', 'CX-5'),
  ('Mazda', 'CX-60'),
  ('Mazda', 'CX-7'),
  ('Mazda', 'CX-9'),
  ('Mazda', 'Demio'),
  ('Mazda', 'MPV'),
  ('Mazda', 'MX-3'),
  ('Mazda', 'MX-5'),
  ('Mazda', 'MX-6'),
  ('Mazda', 'Premacy'),
  ('Mazda', 'RX-7'),
  ('Mazda', 'RX-8'),
  ('Mazda', 'Xedox 6'),
  ('McLaren', '540C'),
  ('McLaren', '570GT'),
  ('McLaren', '570S'),
  ('McLaren', '600LT'),
  ('McLaren', '650S'),
  ('McLaren', '675LT'),
  ('McLaren', '720S'),
  ('McLaren', '765LT'),
  ('McLaren', 'GT'),
  ('McLaren', 'P1'),
  ('McLaren', 'Senna'),
  ('McLaren', 'Speedtail'),
  ('Mercedes-Benz', '100 D'),
  ('Mercedes-Benz', '115'),
  ('Mercedes-Benz', '124'),
  ('Mercedes-Benz', '126'),
  ('Mercedes-Benz', '190'),
  ('Mercedes-Benz', '190 D'),
  ('Mercedes-Benz', '190 E'),
  ('Mercedes-Benz', '200 - 300'),
  ('Mercedes-Benz', '200 D'),
  ('Mercedes-Benz', '200 E'),
  ('Mercedes-Benz', '210 Van'),
  ('Mercedes-Benz', '210 kombi'),
  ('Mercedes-Benz', '230 - 300 CE Coupé'),
  ('Mercedes-Benz', '260 - 560 SE'),
  ('Mercedes-Benz', '260 - 560 SEL'),
  ('Mercedes-Benz', '310 Van'),
  ('Mercedes-Benz', '310 kombi'),
  ('Mercedes-Benz', '500 - 600 SEC Coupé'),
  ('Mercedes-Benz', 'A'),
  ('Mercedes-Benz', 'A L'),
  ('Mercedes-Benz', 'AMG GT'),
  ('Mercedes-Benz', 'C'),
  ('Mercedes-Benz', 'C Sportcoupé'),
  ('Mercedes-Benz', 'C T'),
  ('Mercedes-Benz', 'Citan'),
  ('Mercedes-Benz', 'CLA'),
  ('Mercedes-Benz', 'CLC'),
  ('Mercedes-Benz', 'CLK Cabrio'),
  ('Mercedes-Benz', 'CLK Coupé'),
  ('Mercedes-Benz', 'CLS'),
  ('Mercedes-Benz', 'E'),
  ('Mercedes-Benz', 'E Cabrio'),
  ('Mercedes-Benz', 'E Coupé'),
  ('Mercedes-Benz', 'E T'),
  ('Mercedes-Benz', 'EQC'),
  ('Mercedes-Benz', 'EQS'),
  ('Mercedes-Benz', 'G'),
  ('Mercedes-Benz', 'G Cabrio'),
  ('Mercedes-Benz', 'GL'),
  ('Mercedes-Benz', 'GLA'),
  ('Mercedes-Benz', 'GLB'),
  ('Mercedes-Benz', 'GLC'),
  ('Mercedes-Benz', 'GLE'),
  ('Mercedes-Benz', 'GLK'),
  ('Mercedes-Benz', 'LS'),
  ('Mercedes-Benz', 'LX'),
  ('Mercedes-Benz', 'M'),
  ('Mercedes-Benz', 'R'),
  ('Mercedes-Benz', 'S'),
  ('Mercedes-Benz', 'S Coupé'),
  ('Mercedes-Benz', 'SC'),
  ('Mercedes-Benz', 'SL'),
  ('Mercedes-Benz', 'SLC'),
  ('Mercedes-Benz', 'SLK'),
  ('Mercedes-Benz', 'SLR'),
  ('Mercedes-Benz', 'Sprinter'),
  ('MG', '3'),
  ('MG', '5'),
  ('MG', '6'),
  ('MG', 'Astor'),
  ('MG', 'Cyberster'),
  ('MG', 'Gloster'),
  ('MG', 'Hector'),
  ('MG', 'ZS'),
  ('MG', 'ZS EV'),
  ('MINI', 'Cooper'),
  ('MINI', 'Cooper Cabrio'),
  ('MINI', 'Cooper Clubman'),
  ('MINI', 'Cooper D'),
  ('MINI', 'Cooper D Clubman'),
  ('MINI', 'Cooper S'),
  ('MINI', 'Cooper S Cabrio'),
  ('MINI', 'Cooper S Clubman'),
  ('MINI', 'Countryman'),
  ('MINI', 'Mini One'),
  ('MINI', 'One D'),
  ('Mitsubishi', '3000 GT'),
  ('Mitsubishi', 'ASX'),
  ('Mitsubishi', 'Carisma'),
  ('Mitsubishi', 'Colt'),
  ('Mitsubishi', 'Colt CC'),
  ('Mitsubishi', 'Eclipse'),
  ('Mitsubishi', 'Eclipse Cross'),
  ('Mitsubishi', 'Fuso canter'),
  ('Mitsubishi', 'Galant'),
  ('Mitsubishi', 'Galant Combi'),
  ('Mitsubishi', 'Grandis'),
  ('Mitsubishi', 'L200'),
  ('Mitsubishi', 'L200 Pick up'),
  ('Mitsubishi', 'L200 Pick up Allrad'),
  ('Mitsubishi', 'L300'),
  ('Mitsubishi', 'Lancer'),
  ('Mitsubishi', 'Lancer Combi'),
  ('Mitsubishi', 'Lancer Evo'),
  ('Mitsubishi', 'Lancer Sportback'),
  ('Mitsubishi', 'Outlander'),
  ('Mitsubishi', 'Pajero'),
  ('Mitsubishi', 'Pajero Pinin'),
  ('Mitsubishi', 'Pajero Pinin Wagon'),
  ('Mitsubishi', 'Pajero Sport'),
  ('Mitsubishi', 'Pajero Wagon'),
  ('Mitsubishi', 'Space Star'),
  ('Mullen Automotive', 'FIVE'),
  ('Mullen Automotive', 'MXE'),
  ('Neta Auto', 'GT'),
  ('Neta Auto', 'N01'),
  ('Neta Auto', 'S'),
  ('Neta Auto', 'U'),
  ('Neta Auto', 'V'),
  ('Neta Auto', 'V-II'),
  ('Neta Auto', 'X'),
  ('NEVS', 'NEVS 3'),
  ('NEVS', 'NEVS 9'),
  ('Nikola', 'Badger'),
  ('Nikola', 'Tre'),
  ('Nikola', 'Two'),
  ('NIO', 'EC6'),
  ('NIO', 'EP9'),
  ('NIO', 'ES6'),
  ('NIO', 'ES7'),
  ('NIO', 'ES8'),
  ('NIO', 'ES9'),
  ('NIO', 'ET5'),
  ('NIO', 'ET7'),
  ('Nissan', '100 NX'),
  ('Nissan', '200 SX'),
  ('Nissan', '350 Z'),
  ('Nissan', '370 Z'),
  ('Nissan', 'Almera'),
  ('Nissan', 'Almera Tino'),
  ('Nissan', 'GT-R'),
  ('Nissan', 'Interstar'),
  ('Nissan', 'Juke'),
  ('Nissan', 'King Cab'),
  ('Nissan', 'Leaf'),
  ('Nissan', 'Maxima'),
  ('Nissan', 'Micra'),
  ('Nissan', 'Murano'),
  ('Nissan', 'Navara'),
  ('Nissan', 'Note'),
  ('Nissan', 'NP300 Pickup'),
  ('Nissan', 'NV200'),
  ('Nissan', 'NV400'),
  ('Nissan', 'Pathfinder'),
  ('Nissan', 'Patrol'),
  ('Nissan', 'Pick Up'),
  ('Nissan', 'Primastar'),
  ('Nissan', 'Primera'),
  ('Nissan', 'Pulsar'),
  ('Nissan', 'Qashqai'),
  ('Nissan', 'Serena'),
  ('Nissan', 'Terrano'),
  ('Nissan', 'Tiida'),
  ('Nissan', 'Trade'),
  ('Nissan', 'Vanette Cargo'),
  ('Nissan', 'X-Trail'),
  ('Opel', 'Agila'),
  ('Opel', 'Ampera'),
  ('Opel', 'Antara'),
  ('Opel', 'Astra'),
  ('Opel', 'Astra cabrio'),
  ('Opel', 'Astra caravan'),
  ('Opel', 'Astra coupé'),
  ('Opel', 'Astra Electric'),
  ('Opel', 'Calibra'),
  ('Opel', 'Campo'),
  ('Opel', 'Cascada'),
  ('Opel', 'Corsa'),
  ('Opel', 'Crossland'),
  ('Opel', 'Frontera'),
  ('Opel', 'Grandland'),
  ('Opel', 'Insignia'),
  ('Opel', 'Insignia kombi'),
  ('Opel', 'Kadett'),
  ('Opel', 'Meriva'),
  ('Opel', 'Mokka'),
  ('Opel', 'Mokka-e'),
  ('Opel', 'Movano'),
  ('Opel', 'Omega'),
  ('Opel', 'Signum'),
  ('Opel', 'Vectra'),
  ('Opel', 'Vectra Caravan'),
  ('Opel', 'Vivaro'),
  ('Opel', 'Vivaro Kombi'),
  ('Opel', 'Zafira'),
  ('Opel', 'Zafira Life'),
  ('Ora', 'Black Cat'),
  ('Ora', 'Good Cat'),
  ('Ora', 'Lightning Cat'),
  ('Ora', 'Punk Cat'),
  ('Pagani', 'Huayra'),
  ('Pagani', 'Huayra BC'),
  ('Pagani', 'Huayra Imola'),
  ('Pagani', 'Huayra Roadster'),
  ('Pagani', 'Zonda'),
  ('Perodua', 'Alza'),
  ('Perodua', 'Aruz'),
  ('Perodua', 'Axia'),
  ('Perodua', 'Bezza'),
  ('Perodua', 'Kelisa'),
  ('Perodua', 'Kembara'),
  ('Perodua', 'Myvi'),
  ('Perodua', 'Viva'),
  ('Peugeot', '1007'),
  ('Peugeot', '106'),
  ('Peugeot', '107'),
  ('Peugeot', '108'),
  ('Peugeot', '2008'),
  ('Peugeot', '205'),
  ('Peugeot', '205 Cabrio'),
  ('Peugeot', '206'),
  ('Peugeot', '206 CC'),
  ('Peugeot', '206 SW'),
  ('Peugeot', '207'),
  ('Peugeot', '207 CC'),
  ('Peugeot', '207 SW'),
  ('Peugeot', '208'),
  ('Peugeot', '3008 Hybrid'),
  ('Peugeot', '306'),
  ('Peugeot', '307'),
  ('Peugeot', '307 CC'),
  ('Peugeot', '307 SW'),
  ('Peugeot', '308'),
  ('Peugeot', '308 CC'),
  ('Peugeot', '308 Hybrid'),
  ('Peugeot', '308 SW'),
  ('Peugeot', '309'),
  ('Peugeot', '4007'),
  ('Peugeot', '4008'),
  ('Peugeot', '405'),
  ('Peugeot', '406'),
  ('Peugeot', '407'),
  ('Peugeot', '407 SW'),
  ('Peugeot', '408'),
  ('Peugeot', '5008'),
  ('Peugeot', '5008 Hybrid'),
  ('Peugeot', '508'),
  ('Peugeot', '508 PSE'),
  ('Peugeot', '508 SW'),
  ('Peugeot', '605'),
  ('Peugeot', '607'),
  ('Peugeot', '806'),
  ('Peugeot', '807'),
  ('Peugeot', 'Bipper'),
  ('Peugeot', 'e-2008'),
  ('Peugeot', 'e-208'),
  ('Peugeot', 'RCZ'),
  ('Piech Automotive', 'GT'),
  ('Piech Automotive', 'Mark Zero'),
  ('Polestar', 'Polestar 1'),
  ('Polestar', 'Polestar 2'),
  ('Polestar', 'Polestar 3'),
  ('Polestar', 'Polestar 4'),
  ('Polestar', 'Polestar 5'),
  ('Polestar', 'Polestar 6'),
  ('Porsche', '911 Carrera'),
  ('Porsche', '911 Carrera Cabrio'),
  ('Porsche', '911 Targa'),
  ('Porsche', '911 Turbo'),
  ('Porsche', '924'),
  ('Porsche', '944'),
  ('Porsche', 'Boxster'),
  ('Porsche', 'Cayenne'),
  ('Porsche', 'Cayman'),
  ('Porsche', 'Macan'),
  ('Porsche', 'Panamera'),
  ('Porsche', 'Taycan'),
  ('Proton', 'Exora'),
  ('Proton', 'Iriz'),
  ('Proton', 'Persona'),
  ('Proton', 'Preve'),
  ('Proton', 'Saga'),
  ('Proton', 'X50'),
  ('Proton', 'X70'),
  ('Qoros', 'Qoros 3'),
  ('Qoros', 'Qoros 9'),
  ('Ram', '1500'),
  ('Ram', '1500 TRX'),
  ('Ram', '2500'),
  ('Ram', '3500'),
  ('Ram', 'ProMaster'),
  ('Ram', 'ProMaster City'),
  ('Renault', 'Arkana'),
  ('Renault', 'Austral'),
  ('Renault', 'Captur'),
  ('Renault', 'Clio'),
  ('Renault', 'Clio Grandtour'),
  ('Renault', 'Espace'),
  ('Renault', 'Express'),
  ('Renault', 'Fluence'),
  ('Renault', 'Grand Espace'),
  ('Renault', 'Grand Modus'),
  ('Renault', 'Grand Scenic'),
  ('Renault', 'Kadjar'),
  ('Renault', 'Kangoo'),
  ('Renault', 'Kangoo Express'),
  ('Renault', 'Kiger'),
  ('Renault', 'Koleos'),
  ('Renault', 'Laguna'),
  ('Renault', 'Laguna Grandtour'),
  ('Renault', 'Latitude'),
  ('Renault', 'Mascott'),
  ('Renault', 'Megane E-Tech'),
  ('Renault', 'Mégane'),
  ('Renault', 'Mégane CC'),
  ('Renault', 'Mégane Combi'),
  ('Renault', 'Mégane Coupé'),
  ('Renault', 'Mégane Grandtour'),
  ('Renault', 'Mégane Scénic'),
  ('Renault', 'Scénic'),
  ('Renault', 'Talisman'),
  ('Renault', 'Talisman Grandtour'),
  ('Renault', 'Thalia'),
  ('Renault', 'Triber'),
  ('Renault', 'Twingo'),
  ('Renault', 'Wind'),
  ('Renault', 'Zoé'),
  ('Rezvani', 'Beast'),
  ('Rezvani', 'Tank'),
  ('Rezvani', 'Vengeance'),
  ('Rimac', 'Concept One'),
  ('Rimac', 'Nevera'),
  ('Rising Auto', 'R3'),
  ('Rising Auto', 'R7'),
  ('Rising Auto', 'R9'),
  ('Rivian', 'R1S'),
  ('Rivian', 'R1T'),
  ('Roewe', 'Ei5'),
  ('Roewe', 'i6'),
  ('Roewe', 'RX5'),
  ('Roewe', 'RX6'),
  ('Rolls-Royce', 'Cullinan'),
  ('Rolls-Royce', 'Dawn'),
  ('Rolls-Royce', 'Ghost'),
  ('Rolls-Royce', 'Phantom'),
  ('Rolls-Royce', 'Wraith'),
  ('Rover', '200'),
  ('Rover', '214'),
  ('Rover', '218'),
  ('Rover', '25'),
  ('Rover', '400'),
  ('Rover', '414'),
  ('Rover', '416'),
  ('Rover', '620'),
  ('Rover', '75'),
  ('Saab', '9-3'),
  ('Saab', '9-3 Cabriolet'),
  ('Saab', '9-3 Coupé'),
  ('Saab', '9-3 SportCombi'),
  ('Saab', '9-5'),
  ('Saab', '9-5 SportCombi'),
  ('Saab', '900'),
  ('Saab', '900 C'),
  ('Saab', '900 C Turbo'),
  ('Saab', '9000'),
  ('Seat', 'Alhambra'),
  ('Seat', 'Altea'),
  ('Seat', 'Altea XL'),
  ('Seat', 'Arona'),
  ('Seat', 'Arosa'),
  ('Seat', 'Ateca'),
  ('Seat', 'Cordoba'),
  ('Seat', 'Cordoba Vario'),
  ('Seat', 'Exeo'),
  ('Seat', 'Exeo ST'),
  ('Seat', 'Ibiza'),
  ('Seat', 'Ibiza ST'),
  ('Seat', 'Inca'),
  ('Seat', 'Leon'),
  ('Seat', 'Leon ST'),
  ('Seat', 'Mii'),
  ('Seat', 'Tarraco'),
  ('Seat', 'Toledo'),
  ('Seres', '3'),
  ('Seres', '5'),
  ('Seres', '7'),
  ('Singulato', 'iS6'),
  ('Singulato', 'iS7'),
  ('Skywell', 'ET5'),
  ('Smart', 'Cabrio'),
  ('Smart', 'City-Coupé'),
  ('Smart', 'Compact Pulse'),
  ('Smart', 'Forfour'),
  ('Smart', 'Fortwo cabrio'),
  ('Smart', 'Fortwo coupé'),
  ('Smart', 'Roadster'),
  ('Subaru', 'BRZ'),
  ('Subaru', 'Forester'),
  ('Subaru', 'Impreza'),
  ('Subaru', 'Impreza Wagon'),
  ('Subaru', 'Justy'),
  ('Subaru', 'Legacy'),
  ('Subaru', 'Legacy Outback'),
  ('Subaru', 'Levorg'),
  ('Subaru', 'Outback'),
  ('Subaru', 'SVX'),
  ('Subaru', 'Tribeca'),
  ('Subaru', 'Tribeca B9'),
  ('Subaru', 'WRX'),
  ('Subaru', 'WRX STI'),
  ('Subaru', 'XV'),
  ('Suzuki', 'Alto'),
  ('Suzuki', 'Baleno'),
  ('Suzuki', 'Baleno kombi'),
  ('Suzuki', 'Celerio'),
  ('Suzuki', 'Ertiga'),
  ('Suzuki', 'Grand Vitara'),
  ('Suzuki', 'Grand Vitara XL-7'),
  ('Suzuki', 'Ignis'),
  ('Suzuki', 'Jimny'),
  ('Suzuki', 'Kizashi'),
  ('Suzuki', 'Liana'),
  ('Suzuki', 'Samurai'),
  ('Suzuki', 'Splash'),
  ('Suzuki', 'Swift'),
  ('Suzuki', 'SX4'),
  ('Suzuki', 'SX4 Sedan'),
  ('Suzuki', 'S-Cross'),
  ('Suzuki', 'Vitara'),
  ('Suzuki', 'Wagon R+'),
  ('Škoda', 'Citigo'),
  ('Škoda', 'Enyaq'),
  ('Škoda', 'Fabia'),
  ('Škoda', 'Fabia Combi'),
  ('Škoda', 'Fabia Sedan'),
  ('Škoda', 'Favorit'),
  ('Škoda', 'Felicia'),
  ('Škoda', 'Karoq'),
  ('Škoda', 'Kodiaq'),
  ('Škoda', 'Octavia'),
  ('Škoda', 'Octavia Combi'),
  ('Škoda', 'Roomster'),
  ('Škoda', 'Superb'),
  ('Škoda', 'Superb Combi'),
  ('Tata Motors', 'Altroz'),
  ('Tata Motors', 'Harrier'),
  ('Tata Motors', 'Hexa'),
  ('Tata Motors', 'Nexon'),
  ('Tata Motors', 'Punch'),
  ('Tata Motors', 'Safari'),
  ('Tata Motors', 'Tigor'),
  ('Tata Motors', 'Tiago'),
  ('Tata Motors', 'Zest'),
  ('Tesla', 'Cybercab'),
  ('Tesla', 'Cybertruck'),
  ('Tesla', 'Model 3'),
  ('Tesla', 'Model S'),
  ('Tesla', 'Model X'),
  ('Tesla', 'Model Y'),
  ('Tesla', 'Roadster'),
  ('Thunder Power', 'Sedan'),
  ('Thunder Power', 'SUV'),
  ('Toyota', '4-Runner'),
  ('Toyota', 'Auris'),
  ('Toyota', 'Avensis'),
  ('Toyota', 'Avensis Combi'),
  ('Toyota', 'Avensis Van Verso'),
  ('Toyota', 'Aygo'),
  ('Toyota', 'Camry'),
  ('Toyota', 'Carina'),
  ('Toyota', 'Celica'),
  ('Toyota', 'Corolla'),
  ('Toyota', 'Corolla Combi'),
  ('Toyota', 'Corolla sedan'),
  ('Toyota', 'Corolla Verso'),
  ('Toyota', 'FJ Cruiser'),
  ('Toyota', 'GT86'),
  ('Toyota', 'Hiace'),
  ('Toyota', 'Hiace Van'),
  ('Toyota', 'Highlander'),
  ('Toyota', 'Hilux'),
  ('Toyota', 'Land Cruiser'),
  ('Toyota', 'MR2'),
  ('Toyota', 'Paseo'),
  ('Toyota', 'Picnic'),
  ('Toyota', 'Prius'),
  ('Toyota', 'RAV4'),
  ('Toyota', 'Sequoia'),
  ('Toyota', 'Starlet'),
  ('Toyota', 'Supra'),
  ('Toyota', 'Tundra'),
  ('Toyota', 'Urban Cruiser'),
  ('Toyota', 'Verso'),
  ('Toyota', 'Yaris'),
  ('Toyota', 'Yaris Cross'),
  ('Toyota', 'Yaris Verso'),
  ('Trumpchi', 'ES6'),
  ('Trumpchi', 'GE3'),
  ('Trumpchi', 'GE3 Plus'),
  ('Trumpchi', 'GS4'),
  ('Trumpchi', 'GS8'),
  ('VinFast', 'VF 5'),
  ('VinFast', 'VF 6'),
  ('VinFast', 'VF 7'),
  ('VinFast', 'VF 8'),
  ('VinFast', 'VF 9'),
  ('Volkswagen', 'Amarok'),
  ('Volkswagen', 'Beetle'),
  ('Volkswagen', 'Bora'),
  ('Volkswagen', 'Bora Variant'),
  ('Volkswagen', 'Caddy'),
  ('Volkswagen', 'Caddy Van'),
  ('Volkswagen', 'California'),
  ('Volkswagen', 'Caravelle'),
  ('Volkswagen', 'CC'),
  ('Volkswagen', 'Crafter'),
  ('Volkswagen', 'Crafter Kombi'),
  ('Volkswagen', 'Crafter Van'),
  ('Volkswagen', 'CrossTouran'),
  ('Volkswagen', 'Eos'),
  ('Volkswagen', 'Fox'),
  ('Volkswagen', 'Golf'),
  ('Volkswagen', 'Golf Cabrio'),
  ('Volkswagen', 'Golf Plus'),
  ('Volkswagen', 'Golf Sportvan'),
  ('Volkswagen', 'Golf Variant'),
  ('Volkswagen', 'ID. Buzz'),
  ('Volkswagen', 'ID.3'),
  ('Volkswagen', 'ID.4'),
  ('Volkswagen', 'ID.5'),
  ('Volkswagen', 'Jetta'),
  ('Volkswagen', 'LT'),
  ('Volkswagen', 'Lupo'),
  ('Volkswagen', 'Multivan'),
  ('Volkswagen', 'New Beetle'),
  ('Volkswagen', 'New Beetle Cabrio'),
  ('Volkswagen', 'Passat'),
  ('Volkswagen', 'Passat Alltrack'),
  ('Volkswagen', 'Passat CC'),
  ('Volkswagen', 'Passat Variant'),
  ('Volkswagen', 'Passat Variant Van'),
  ('Volkswagen', 'Phaeton'),
  ('Volkswagen', 'Polo'),
  ('Volkswagen', 'Polo Van'),
  ('Volkswagen', 'Polo Variant'),
  ('Volkswagen', 'Scirocco'),
  ('Volkswagen', 'Sharan'),
  ('Volkswagen', 'T4'),
  ('Volkswagen', 'T4 Caravelle'),
  ('Volkswagen', 'T4 Multivan'),
  ('Volkswagen', 'T5'),
  ('Volkswagen', 'Tera'),
  ('Volkswagen', 'Tiguan'),
  ('Volkswagen', 'Touareg'),
  ('Volkswagen', 'Touran'),
  ('Volvo', '240'),
  ('Volvo', '340'),
  ('Volvo', '360'),
  ('Volvo', '460'),
  ('Volvo', '850'),
  ('Volvo', '850 kombi'),
  ('Volvo', 'C30'),
  ('Volvo', 'C70'),
  ('Volvo', 'C70 Cabrio'),
  ('Volvo', 'C70 Coupé'),
  ('Volvo', 'S40'),
  ('Volvo', 'S60'),
  ('Volvo', 'S70'),
  ('Volvo', 'S80'),
  ('Volvo', 'S90'),
  ('Volvo', 'V40'),
  ('Volvo', 'V50'),
  ('Volvo', 'V60'),
  ('Volvo', 'V70'),
  ('Volvo', 'V90'),
  ('Volvo', 'XC40'),
  ('Volvo', 'XC60'),
  ('Volvo', 'XC70'),
  ('Volvo', 'XC90'),
  ('Voyah', 'Dreamer'),
  ('Voyah', 'Free'),
  ('Voyah', 'Passion'),
  ('Voyah', 'Pro'),
  ('Weltmeister', 'E5'),
  ('Weltmeister', 'EX5'),
  ('Weltmeister', 'EX6 Plus'),
  ('Weltmeister', 'W6'),
  ('Wuling', 'Air EV'),
  ('Wuling', 'Almaz'),
  ('Wuling', 'Alvez'),
  ('Wuling', 'Cortez'),
  ('Wuling', 'Hongguang Mini EV'),
  ('Wuling', 'Victory'),
  ('Xiaomi', 'Kunlun'),
  ('Xiaomi', 'MS11'),
  ('Xiaomi', 'MS12'),
  ('Xiaomi', 'MX11'),
  ('Xiaomi', 'SU7'),
  ('XPeng', 'G3'),
  ('XPeng', 'G6'),
  ('XPeng', 'P5'),
  ('XPeng', 'P7'),
  ('XPeng', 'P9'),
  ('XPeng', 'X9'),
  ('Zeekr', '001'),
  ('Zeekr', '003'),
  ('Zeekr', '009'),
  ('Zotye', 'T300'),
  ('Zotye', 'T500'),
  ('Zotye', 'T600'),
  ('Zotye', 'T700'),
  ('Zotye', 'T800'),
  ('Zotye', 'Z100'),
  ('Zotye', 'Z500')
) AS m(brand_name, model_name) ON LOWER(b.name) = LOWER(m.brand_name)
ON CONFLICT (brand_id, name) DO NOTHING;
